#ifndef TYPES_H__
#define TYPES_H__

namespace sum
{

typedef enum 
{
   NORTH,
   EAST,
   SOUTH,
   WEST,
   ALL_DIR
} Direction;

typedef enum {
   BASE_TER_GRASS,
   BASE_TER_MOUNTAIN,
   BASE_TER_UNDERGROUND
} BaseTerrain;

typedef enum {
   TER_NONE,
   // Trees
   TER_TREE1,
   TER_TREE2,
   // Cliffs basic
   CLIFF_SOUTH,
   CLIFF_SOUTH_WEST_EDGE,
   CLIFF_SOUTH_EAST_EDGE,
   CLIFF_NORTH,
   CLIFF_NORTH_EAST_EDGE,
   CLIFF_NORTH_WEST_EDGE,
   CLIFF_EAST,
   CLIFF_EAST_SOUTH_EDGE,
   CLIFF_EAST_NORTH_EDGE,
   CLIFF_WEST,
   CLIFF_WEST_NORTH_EDGE,
   CLIFF_WEST_SOUTH_EDGE,
   // Cliffs corners
   CLIFF_CORNER_SOUTHWEST_90,
   CLIFF_CORNER_SOUTHWEST_270,
   CLIFF_CORNER_SOUTHEAST_90,
   CLIFF_CORNER_SOUTHEAST_270,
   CLIFF_CORNER_NORTHEAST_90,
   CLIFF_CORNER_NORTHEAST_270,
   CLIFF_CORNER_NORTHWEST_90,
   CLIFF_CORNER_NORTHWEST_270,
   // End
   NUM_TERRAINS
} Terrain;

typedef enum {
   VIS_NONE,
   VIS_OFFMAP,
   VIS_NEVER_SEEN,
   VIS_SEEN_BEFORE,
   VIS_VISIBLE
} Vision;

};

#endif 
