#ifndef TYPES_H__
#define TYPES_H__

namespace sum
{

typedef enum 
{
   NORTH,
   EAST,
   SOUTH,
   WEST,
   ALL_DIR
} Direction;

typedef enum {
   DMG_NORMAL,
   DMG_HEAVY,
   DMG_LIGHT,
   DMG_POISON,
   DMG_FIRE,
   DMG_HEAL
} DamageType;

typedef enum {
   BASE_TER_GRASS,
   BASE_TER_MOUNTAIN,
   BASE_TER_UNDERGROUND
} BaseTerrain;

#define FLAG_VIS_TREESIGHT_MASK 0xf
#define FLAG_VIS_FLYING 0x10

//////////////////////////////////////////////////////////////////////
// Keybind targets ---

typedef enum
{
   KB_NOTHING,

   KB_FORCE_QUIT,

   KB_PAUSE,

   // Camera
   KB_MOVE_CAMERA_LEFT,
   KB_MOVE_CAMERA_UP,
   KB_MOVE_CAMERA_RIGHT,
   KB_MOVE_CAMERA_DOWN,
   KB_ZOOM_OUT_CAMERA,
   KB_ZOOM_IN_CAMERA,

   KB_TOGGLE_OPTIONS_MENU,

   KB_SHOW_KEYBINDINGS,

   // Debug
   KB_DEBUG_TOGGLE_FOG,
   KB_DEBUG_TOGGLE_FRAMERATE,

   // COUNT BUTTONS
   KB_BTN_COUNT_0,
   KB_BTN_COUNT_1,
   KB_BTN_COUNT_2,
   KB_BTN_COUNT_3,
   KB_BTN_COUNT_4,
   KB_BTN_COUNT_5,
   KB_BTN_COUNT_6,
   KB_BTN_COUNT_7,
   KB_BTN_COUNT_8,
   KB_BTN_COUNT_9,
   KB_BTN_COUNT_CLEAR,
   KB_BTN_COUNT_INFINITE,

   // Condition Buttons
   KB_BTN_COND_ENEMY_ADJACENT,
   KB_BTN_COND_ENEMY_AHEAD,
   KB_BTN_COND_ENEMY_IN_RANGE,
   KB_BTN_COND_HEALTH_UNDER_50,
   KB_BTN_COND_HEALTH_UNDER_20,
   KB_BTN_COND_BLOCKED_AHEAD,
   KB_BTN_COND_CLEAR,

   // ORDER BUTTONS
   // Movement Buttons
   KB_BTN_MOVE_FORWARD,
   KB_BTN_MOVE_BACK,
   KB_BTN_TURN_NORTH,
   KB_BTN_TURN_EAST,
   KB_BTN_TURN_SOUTH,
   KB_BTN_TURN_WEST,
   KB_BTN_TURN_NEAREST_ENEMY,
   KB_BTN_FOLLOW_PATH,
   KB_BTN_WAIT,

   // Basic Fighting Buttons
   KB_BTN_ATTACK_CLOSEST,
   KB_BTN_ATTACK_FARTHEST,
   KB_BTN_ATTACK_BIGGEST,
   KB_BTN_ATTACK_SMALLEST,
   KB_BTN_ATTACK_MOST_ARMORED,
   KB_BTN_ATTACK_LEAST_ARMORED,

   // Basic Control Flow Buttons
   KB_BTN_START_BLOCK,
   KB_BTN_END_BLOCK,
   KB_BTN_REPEAT,

   // Monster Buttons
   KB_BTN_MONSTER_GUARD,
   KB_BTN_MONSTER_BURST,

   // Soldier Buttons
   KB_BTN_SOLDIER_SWITCH_AXE,
   KB_BTN_SOLDIER_SWITCH_SPEAR,
   KB_BTN_SOLDIER_SWITCH_BOW,

   // Worm Buttons
   KB_BTN_WORM_HIDE,
   KB_BTN_WORM_TRAIL_START,
   KB_BTN_WORM_TRAIL_END,

   // Bird Buttons
   KB_BTN_BIRD_CMD_SHOUT,
   KB_BTN_BIRD_CMD_QUIET,
   KB_BTN_BIRD_FLY,

   // Bug Buttons
   KB_BTN_BUG_CAST_FIREBALL,
   KB_BTN_BUG_CAST_SHOCK,
   KB_BTN_BUG_CAST_DUST,
   KB_BTN_BUG_OPEN_WORMHOLE,
   KB_BTN_BUG_CLOSE_WORMHOLE,
   KB_BTN_BUG_MEDITATE,

   // Player Buttons
   // Alert
   KB_BTN_PL_ALERT_ALL,
   KB_BTN_PL_ALERT_MONSTERS,
   KB_BTN_PL_ALERT_SOLDIERS,
   KB_BTN_PL_ALERT_WORMS,
   KB_BTN_PL_ALERT_BIRDS,
   KB_BTN_PL_ALERT_BUGS,
   // Activate
   KB_BTN_PL_GO,
   KB_BTN_PL_GO_ALL,
   KB_BTN_PL_GO_MONSTERS,
   KB_BTN_PL_GO_SOLDIERS,
   KB_BTN_PL_GO_WORMS,
   KB_BTN_PL_GO_BIRDS,
   KB_BTN_PL_GO_BUGS,

   KB_BTN_PL_SET_GROUP,
   KB_BTN_PL_DELAY,

   KB_COUNT
} KeybindTarget;

//////////////////////////////////////////////////////////////////////
// Terrain ---

typedef unsigned char Terrain;
#define TER_NONE 0
   // Cliffs basic (1-12) - 12
#define TER_CLIFF_S 1
#define TER_CLIFF_S_W_EDGE 2
#define TER_CLIFF_S_E_EDGE 3
#define TER_CLIFF_N 4
#define TER_CLIFF_N_E_EDGE 5
#define TER_CLIFF_N_W_EDGE 6
#define TER_CLIFF_E 7
#define TER_CLIFF_E_S_EDGE 8
#define TER_CLIFF_E_N_EDGE 9
#define TER_CLIFF_W 10
#define TER_CLIFF_W_N_EDGE 11
#define TER_CLIFF_W_S_EDGE 12
   // Cliffs corners (13-20) - 8
#define TER_CLIFF_CORNER_SE_90 13
#define TER_CLIFF_CORNER_SW_90 14
#define TER_CLIFF_CORNER_NW_90 15
#define TER_CLIFF_CORNER_NE_90 16
#define TER_CLIFF_CORNER_SE_270 17
#define TER_CLIFF_CORNER_SW_270 18
#define TER_CLIFF_CORNER_NW_270 19
#define TER_CLIFF_CORNER_NE_270 20
   // Rocks (21-40) - 9
#define TER_ROCK_1 21
#define TER_ROCK_2 22
#define TER_ROCK_3 23
#define TER_ROCK_4 24
#define TER_ROCK_5 25
#define TER_ROCK_6 26
#define TER_ROCK_7 27
#define TER_ROCK_8 28
#define TER_ROCK_LAST 29
   // Trees (41-59) - 9
#define TER_TREE_1 41
#define TER_TREE_2 42
#define TER_TREE_3 43
#define TER_TREE_4 44
#define TER_TREE_5 45
#define TER_TREE_6 46
#define TER_TREE_7 47
#define TER_TREE_8 48
#define TER_TREE_LAST 49
   // Flowers/Grass (41-60) - 0

// More special terrain
   // Dirt Path (224-233) - 10
#define TER_PATH_N_END 224
#define TER_PATH_E_END 225
#define TER_PATH_S_END 226
#define TER_PATH_W_END 227
#define TER_PATH_EW 228
#define TER_PATH_NS 229
#define TER_PATH_NE 230
#define TER_PATH_SE 231
#define TER_PATH_SW 232
#define TER_PATH_NW 233
   // Edge Cliffs (234-245) - 12
#define TER_EDGE_CLIFF_N 234
#define TER_EDGE_CLIFF_S 235
#define TER_EDGE_CLIFF_E 236
#define TER_EDGE_CLIFF_W 237
#define TER_EDGE_CLIFF_CORNER_SE_90 238
#define TER_EDGE_CLIFF_CORNER_SW_90 239
#define TER_EDGE_CLIFF_CORNER_NW_90 240
#define TER_EDGE_CLIFF_CORNER_NE_90 241
#define TER_EDGE_CLIFF_CORNER_SE_270 242
#define TER_EDGE_CLIFF_CORNER_SW_270 243
#define TER_EDGE_CLIFF_CORNER_NW_270 244
#define TER_EDGE_CLIFF_CORNER_NE_270 245
   // Atelier (246-254) - 9
#define TER_ATELIER 246
#define TER_ATELIER_N_EDGE 247
#define TER_ATELIER_E_EDGE 248
#define TER_ATELIER_S_EDGE 249
#define TER_ATELIER_W_EDGE 250
#define TER_ATELIER_CORNER_NE 251
#define TER_ATELIER_CORNER_SE 252
#define TER_ATELIER_CORNER_SW 253
#define TER_ATELIER_CORNER_NW 254

#define NUM_TERRAINS 255

//////////////////////////////////////////////////////////////////////
// Terrain Mod ---

typedef enum {
   TM_NONE,
   TM_TRAIL_W_END,
   TM_TRAIL_S_END,
   TM_TRAIL_E_END,
   TM_TRAIL_N_END,
   TM_TRAIL_EW,
   TM_TRAIL_NS,
   TM_TRAIL_NE,
   TM_TRAIL_SE,
   TM_TRAIL_SW,
   TM_TRAIL_NW,
   TM_WH_OPEN_1,
   TM_WH_CLOSE_1,
   TM_WH_OPEN_2,
   TM_WH_CLOSE_2,
   TM_WH_OPEN_3,
   TM_WH_CLOSE_3,
   TM_WH_OPEN_4,
   TM_WH_CLOSE_4,
   TM_WH_OPEN_5,
   TM_WH_CLOSE_5,
   TM_WH_OPEN_6,
   TM_WH_CLOSE_6,
   NUM_TERRAIN_MODS
} TerrainMod;

typedef enum {
   VIS_NONE,
   VIS_OFFMAP,
   VIS_NEVER_SEEN,
   VIS_SEEN_BEFORE,
   VIS_VISIBLE
} Vision;

};

#endif 
